import { Profile } from '@/types';

export const PROFILES: Record<string, Profile> = {
  A: {
    id: 'A',
    name: 'Transactional Operations',
    nameAr: 'العمليات التجارية',
    icon: '🛒',
    color: '#3B82F6',
    colorLight: '#DBEAFE',
    industries: ['Retail', 'Restaurants', 'E-commerce', 'QSR'],
    industriesAr: ['التجزئة', 'المطاعم', 'التجارة الإلكترونية', 'مطاعم الخدمة السريعة'],
    cardCount: 45,
    dashboardCount: 4,
    dashboards: [
      { id: 'A1', name: 'Executive Command Center', nameAr: 'مركز القيادة التنفيذية' },
      { id: 'A2', name: 'Operations Control Room', nameAr: 'غرفة التحكم بالعمليات' },
      { id: 'A3', name: 'Sales & Customer Analytics', nameAr: 'تحليلات المبيعات والعملاء' },
      { id: 'A4', name: 'Strategic & Risk Analysis', nameAr: 'التحليل الاستراتيجي والمخاطر' },
    ],
  },
  B: {
    id: 'B',
    name: 'Service & Appointments',
    nameAr: 'الخدمات والمواعيد',
    icon: '📅',
    color: '#22C55E',
    colorLight: '#DCFCE7',
    industries: ['Clinics', 'Salons', 'Fitness', 'Consulting'],
    industriesAr: ['العيادات', 'الصالونات', 'اللياقة', 'الاستشارات'],
    cardCount: 42,
    dashboardCount: 4,
    dashboards: [
      { id: 'B1', name: 'Executive Overview', nameAr: 'النظرة التنفيذية' },
      { id: 'B2', name: 'Capacity & Resource', nameAr: 'السعة والموارد' },
      { id: 'B3', name: 'Client Analytics', nameAr: 'تحليلات العملاء' },
      { id: 'B4', name: 'Strategic Planning', nameAr: 'التخطيط الاستراتيجي' },
    ],
  },
  C: {
    id: 'C',
    name: 'Pipeline & Sales',
    nameAr: 'خط الأنابيب والمبيعات',
    icon: '📈',
    color: '#8B5CF6',
    colorLight: '#EDE9FE',
    industries: ['B2B Sales', 'Real Estate', 'Insurance', 'Recruitment'],
    industriesAr: ['مبيعات B2B', 'العقارات', 'التأمين', 'التوظيف'],
    cardCount: 40,
    dashboardCount: 4,
    dashboards: [
      { id: 'C1', name: 'Sales Command Center', nameAr: 'مركز قيادة المبيعات' },
      { id: 'C2', name: 'Pipeline Operations', nameAr: 'عمليات خط الأنابيب' },
      { id: 'C3', name: 'Deal Analytics', nameAr: 'تحليلات الصفقات' },
      { id: 'C4', name: 'Strategic Planning', nameAr: 'التخطيط الاستراتيجي' },
    ],
  },
  D: {
    id: 'D',
    name: 'Operations & Process',
    nameAr: 'العمليات والإجراءات',
    icon: '⚙️',
    color: '#F59E0B',
    colorLight: '#FEF3C7',
    industries: ['Government', 'Banks', 'Legal', 'Healthcare Admin'],
    industriesAr: ['الحكومة', 'البنوك', 'القانون', 'إدارة الرعاية الصحية'],
    cardCount: 38,
    dashboardCount: 4,
    dashboards: [
      { id: 'D1', name: 'Operations Command', nameAr: 'قيادة العمليات' },
      { id: 'D2', name: 'Process Analytics', nameAr: 'تحليلات العمليات' },
      { id: 'D3', name: 'Resource Management', nameAr: 'إدارة الموارد' },
      { id: 'D4', name: 'Strategic Operations', nameAr: 'العمليات الاستراتيجية' },
    ],
  },
  E: {
    id: 'E',
    name: 'Content & Text',
    nameAr: 'المحتوى والنصوص',
    icon: '💬',
    color: '#EC4899',
    colorLight: '#FCE7F3',
    industries: ['Support Centers', 'Call Centers', 'Media', 'Market Research'],
    industriesAr: ['مراكز الدعم', 'مراكز الاتصال', 'الإعلام', 'أبحاث السوق'],
    cardCount: 36,
    dashboardCount: 4,
    dashboards: [
      { id: 'E1', name: 'CX Command Center', nameAr: 'مركز قيادة تجربة العملاء' },
      { id: 'E2', name: 'Text Analytics', nameAr: 'تحليلات النصوص' },
      { id: 'E3', name: 'Support Performance', nameAr: 'أداء الدعم' },
      { id: 'E4', name: 'Strategic Insights', nameAr: 'الرؤى الاستراتيجية' },
    ],
  },
  X: {
    id: 'X',
    name: 'Custom Analytics',
    nameAr: 'التحليلات المخصصة',
    icon: '✨',
    color: '#EAB308',
    colorLight: '#FEF9C3',
    industries: ['Enterprise', 'Multi-vertical'],
    industriesAr: ['المؤسسات', 'متعدد القطاعات'],
    cardCount: null,
    dashboardCount: null,
    isPremium: true,
    dashboards: [],
  },
};

export const getProfileById = (id: string): Profile | undefined => PROFILES[id];

export const getAllProfiles = (): Profile[] => Object.values(PROFILES);
